# Configuration File for Travis-CI

language: python
python:
  - "2.7"

install: pip install -r vis/requirements.txt --allow-external music21 --allow-unverified music21

script:  coverage run run_tests.py

after_success: coveralls
